# SITE CONFIGURATION
baseurl: "/blog"
url: "https://fraulyoner.github.io"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: fraulyoner goes agile
  favicon: assets/favicon.ico
  description: "Hier bloggt Frau Lyoner." #used by search engines
  image: "assets/img/logo.jpg"

  # Header text
  header_text:
  header_text_feature_image: #"assets/img/xy.jpg"

  # Icons
  rss: true
  email_address: aljona.buchloh@gmail.com
  instagram: "fraulyoner"
  twitter: "fraulyoner"

  # Search feature
  search: true

  # Post navigation
  post_navigation: true

  # Related posts
  related_posts: true
  related_posts_max: 4
  related_posts_minCommon: 1

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-redirect-from]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
