# SITE CONFIGURATION
baseurl: "/agile"
url: "https://fraulyoner.github.io"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Yet Another Agile Log Book
  description: "Blog über meine Reise zum Agile Coach, auf dem ich nicht nur
  Ideen und Erfahrungen zu Retrospektiven-Formaten festhalte, sondern auch
  persönliche Gedanken und Lessons Learned, die ich während meiner Arbeit als
  Scrum Master gesammelt habe." #used by search engines

  # Icons
  rss: true
  email_address: aljona.buchloh@gmail.com
  instagram: "fraulyoner"
  twitter: "fraulyoner"
  xing: "Aljona_Buchloh"

  # Search feature
  search: true

  # Post navigation
  post_navigation: false

  # Related posts
  related_posts: true
  related_posts_max: 4
  related_posts_minCommon: 1

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-redirect-from]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
