# SITE CONFIGURATION
baseurl: "/agile"
url: "https://fraulyoner.github.io"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Yet Another Agile Blog
  title_short: YAAB
  description: "Blog über meine agile Reise als Scrum Master und Team Coach,
  auf dem ich vor allem Ideen und Erfahrungen zu Retrospektiven und Workshops
  festhalte" #used by search engines

  # Icons
  rss: true
  email_address: hallo@fraulyoner.de
  instagram: "fraulyoner"
  twitter: "fraulyoner"
  xing: "Aljona_Buchloh"
  homepage: "https://fraulyoner.de/"

  # Search feature
  search: true

  # Post navigation
  post_navigation: false

  # Related posts
  related_posts: true
  related_posts_max: 4
  related_posts_minCommon: 1

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-redirect-from]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
